# -*- coding: utf-8 -*-
"""quant berbasis momentum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jGAXMKTc9nXhAz_6vzMRmNAiCwvqz4BF
"""

import pandas as pd
import yfinance as yf
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings('ignore')
plt.style.use('ggplot')

import pandas as pd
import yfinance as yf

# 1. Load data dari Excel
df_ihsg = pd.read_excel("/content/drive/MyDrive/Daftar Saham  - 20251026.xlsx")

# Ambil kolom 'Kode' dan tambahkan akhiran '.JK'
tickers = [str(t) + ".JK" for t in df_ihsg['Kode'].unique().tolist()]

# 2. Konfigurasi Tanggal (Sesuai kebutuhan backtest Anda dari 2009)
start_date = "2024-01-01"
end_date = "2026-06-26"

print(f"Memulai download untuk {len(tickers)} saham...")

# 3. Download Data Secara Massal
df_raw = yf.download(tickers, start=start_date, end=end_date, group_by='ticker')

# 4. Merapikan Data & Mengubah Nama Kolom
# --- SETTING FILTER LIKUIDITAS ---
# Ganti angka ini sesuai keinginan: 1, 2, 5, atau 10 Miliar
MIN_TURNOVER_MILLIARD = 10  # Contoh: 2 Miliar per hari
MIN_TURNOVER_VALUE = MIN_TURNOVER_MILLIARD * 1_000_000_000
all_data = []

for ticker_jk in tickers:
    if ticker_jk in df_raw.columns.levels[0]:
        temp_df = df_raw[ticker_jk].copy()

        # Bersihkan data kosong agar tidak error saat hitung turnover
        temp_df = temp_df.dropna(subset=['Close', 'Volume'])

        if len(temp_df) < 20: # Skip jika data terlalu pendek untuk dihitung rata-ratanya
            continue

        # 1. Hitung Turnover Harian (Harga x Volume)
        temp_df['Turnover'] = temp_df['Close'] * temp_df['Volume']

        # 2. Hitung Rata-rata Turnover 20 Hari (sekitar 1 bulan bursa)
        # Gunakan .mean() untuk mendapatkan angka rata-rata terakhir
        avg_turnover_now = temp_df['Turnover'].rolling(window=20).mean().iloc[-1]

        # 3. KEPUTUSAN: Masuk atau Drop?
        if avg_turnover_now >= MIN_TURNOVER_VALUE:
            temp_df.rename(columns={'Close': 'PriceClose'}, inplace=True)
            temp_df['Ticker'] = ticker_jk.replace(".JK", "")
            temp_df.reset_index(inplace=True)
            all_data.append(temp_df)
        else:
            # Saham yang sepi (Lapis 3 sepi) tidak akan masuk ke list all_data
            continue

# 5. Gabungkan semua hasil
if all_data:
    data = pd.concat(all_data, ignore_index=True)

    # Memastikan kolom 'Date' bertipe datetime (Penting untuk merge nanti)
    data['Date'] = pd.to_datetime(data['Date'])

    print("Download Selesai!")
    print(f"Kolom yang tersedia: {data.columns.tolist()}")
else:
    print("Tidak ada data yang berhasil di-download.")

display(data.head())

data['Ticker'].unique()

len(data['Ticker'].unique())

stocks_data = data[['Ticker','Date','PriceClose']].copy()
stocks_data.head(3)

def calculate_momentum(data) :
  """Calculate Momentum using T-12 Month up to T-2 Month Return"""
  data = data.copy()
  data['FactorMomentum'] = data.groupby('Ticker')['PriceClose'].transform(lambda x: (x.shift(2) - x.shift(12)) / x.shift(12))
  return data

stocks_data = calculate_momentum(data = stocks_data)
stocks_data.head(13)

def calculate_reversal(data):
    """Calculate Reversal using previous month return"""
    data = data.copy()
    # Perubahan: Menambahkan tanda minus (-) di depan untuk mencerminkan logika Reversal
    data['FactorReversal'] = data.groupby('Ticker')['PriceClose'].transform(
        lambda x: -((x.shift(1) - x.shift(2)) / x.shift(2))
    )
    return data

stocks_data = calculate_reversal(data = stocks_data)
stocks_data.head(13)

def calculate_lag_return(data):
    """Calculate Lag Return using previous 6 month return"""
    data = data.copy()
    # Perubahan: Logika shift disesuaikan untuk mengambil return akumulatif 6 bulan,
    # bukan hanya return 1 bulan yang terjadi 6 bulan lalu.
    data['FactorLagReturn-6M'] = data.groupby('Ticker')['PriceClose'].transform(
        lambda x: (x.shift(1) - x.shift(7)) / x.shift(7)
    )
    return data

stocks_data = calculate_lag_return(data = stocks_data)
stocks_data.head(13)

def calculate_next_month_return(data):
    """Calculate Next Month Return (Target Variable)"""
    data = data.copy()
    # Mekanisme: Menghitung return satu periode ke depan
    data['Rt+1'] = data.groupby('Ticker')['PriceClose'].transform(lambda x: (x.shift(-1) - x) / x)

    # Perubahan: Menggunakan dropna() atau fillna(0) daripada fillna(-1)
    # Menghapus baris terakhir per ticker karena kita tidak tahu masa depan (Rt+1 tidak ada)
    data = data.dropna(subset=['Rt+1'])

    return data

stocks_data = calculate_next_month_return(data=stocks_data)

cols_preserved = ['Ticker', 'Date', 'FactorMomentum',
                  'FactorReversal','FactorLagReturn-6M', 'Rt+1']

stocks_data = stocks_data.loc[
                              :,
                              cols_preserved
                              ]
stocks_data.head(2)

# 1. Filter date
start_period = start_date
end_period = end_date
stocks_data = stocks_data.loc[
    (stocks_data['Date'] >= start_period) &
    (stocks_data['Date'] <= end_period)
]

# 2. Perubahan Tambahan: Membersihkan data dari NaN
# Mekanisme: Menghapus baris yang tidak memiliki data lengkap akibat proses shifting
stocks_data = stocks_data.dropna()

# Cek hasil akhir
print(f"Jumlah baris setelah dibersihkan: {len(stocks_data)}")
stocks_data.head(5)

buffer_n_year = 1

# Perubahan: initial_buffer_start sebaiknya langsung menggunakan start_period
# Mekanisme: Agar data bulan pertama (Januari) tidak terbuang sia-sia
initial_buffer_start = pd.to_datetime(start_date)
initial_buffer_end = pd.to_datetime(start_date) + pd.offsets.YearEnd(n=buffer_n_year)

print(f"Training Awal Mulai: {initial_buffer_start}")
print(f"Training Awal Selesai: {initial_buffer_end}")

# Mekanisme: Mengambil data untuk training awal (Initial Buffer)
buffer_data = stocks_data.loc[
    (stocks_data['Date'] >= initial_buffer_start) &
    (stocks_data['Date'] <= initial_buffer_end)
].copy()

# Perubahan Tambahan: Pengecekan Ketersediaan Data
if buffer_data.empty:
    print("Peringatan: buffer_data kosong! Periksa kembali rentang tanggal initial_buffer.")
else:
    print(f"Berhasil mengambil {len(buffer_data)} baris data untuk training awal.")
    print(f"Rentang Data: {buffer_data['Date'].min()} s/d {buffer_data['Date'].max()}")

buffer_data.head()

feature = ['FactorMomentum', 'FactorReversal', 'FactorLagReturn-6M']

# 1. Pemisahan Fitur dan Target
X_buffer = buffer_data.loc[:, feature]
y_buffer = buffer_data['Rt+1']

# 2. Perubahan Tambahan: Standarisasi Fitur (Feature Scaling)
# Mekanisme: Mengubah skala fitur agar memiliki rata-rata 0 dan varians 1
scaler = StandardScaler()
X_buffer_scaled = scaler.fit_transform(X_buffer)

# Mengembalikan ke bentuk DataFrame agar mudah dibaca
X_buffer = pd.DataFrame(X_buffer_scaled, columns=feature, index=X_buffer.index)

print("Statistik X_buffer setelah standarisasi:")
print(X_buffer.describe().round(2))

def get_training_data(data,
                      initial_buffer_start,
                      initial_buffer_end,
                      feature_cols):
    data = data.copy()

    # 1. Filter periode buffer
    training_data = data.loc[
        (data['Date'] >= initial_buffer_start) &
        (data['Date'] <= initial_buffer_end)
    ]

    # 2. Perubahan: Membersihkan baris yang mengandung NaN
    # Mekanisme: Shift 12 bulan menyebabkan baris awal kosong.
    # RF tidak bisa memproses NaN.
    training_data = training_data.dropna(subset=feature_cols + ['Rt+1'])

    if training_data.empty:
        return None, None, None

    # 3. Pemisahan Fitur dan Target
    X_train = training_data.loc[:, feature_cols]
    y_train = training_data['Rt+1']

    # 4. Perubahan: Menambahkan Feature Scaling
    # Mekanisme: Menyamakan skala agar FactorMomentum tidak mendominasi FactorReversal.
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)

    # Mengembalikan ke DataFrame agar tetap memiliki nama kolom
    X_train = pd.DataFrame(X_train_scaled, columns=feature_cols, index=X_train.index)

    return X_train, y_train, scaler

# Cara memanggilnya:
# X_train, y_train, model_scaler = get_training_data(stocks_data, start, end, feature)

# Perubahan 1: Penyesuaian Unpacking (Menambah variabel scaler)
# Karena fungsi get_training_data yang baru mengembalikan 3 hal: X, y, dan scaler.
X_buffer, y_buffer, model_scaler = get_training_data(
    data = stocks_data,
    initial_buffer_start = initial_buffer_start,
    initial_buffer_end = initial_buffer_end,
    feature_cols = feature
)

# Perubahan 2: Pengecekan Integritas (Mencegah error di tahap model.fit)
if X_buffer is not None:
    print(f"X_buffer siap dengan shape: {X_buffer.shape}")
    print(f"y_buffer siap dengan shape: {y_buffer.shape}")
else:
    print("Gagal mengambil data training. Periksa rentang tanggal atau ketersediaan data.")

X_buffer

y_buffer

from sklearn.ensemble import RandomForestRegressor

def train_ml_model(X_train, y_train):
    """
    Mekanisme: Melatih model dengan pembatasan kompleksitas (Regularization)
    untuk menghindari overfitting pada data noise pasar saham.
    """
    # Perubahan: Menambahkan parameter max_depth dan min_samples_leaf
    model = RandomForestRegressor(
        n_estimators=100,      # Jumlah pohon ditambah agar hasil lebih stabil (voting lebih banyak)
        max_depth=5,           # MEMBATASI kedalaman agar tidak menghafal noise (overfit)
        min_samples_leaf=10,   # Memastikan pola yang diambil cukup umum (bukan anomali)
        random_state=42,
        n_jobs=-1              # Menggunakan seluruh core CPU untuk kecepatan
    )

    model.fit(X_train, y_train)
    return model

model = train_ml_model(X_train = X_buffer,
                       y_train = y_buffer)

first_porto_date = (initial_buffer_end + \
               pd.offsets.MonthEnd(n=1)) # it should yield 2011-01-31
print('first porto construction date',first_porto_date)

# 1. Select data fitur (X)
X_porto = stocks_data.loc[
    (stocks_data['Date'] == first_porto_date), feature
]

# Perubahan: WAJIB melakukan scaling pada X_porto menggunakan scaler dari data training
# Mekanisme: Agar skala data Januari 2011 sama dengan standar yang dipelajari model (2009-2010)
X_porto_scaled = model_scaler.transform(X_porto) # Gunakan transform, BUKAN fit_transform
X_porto = pd.DataFrame(X_porto_scaled, columns=feature, index=X_porto.index)

# 2. Select data identitas
y_porto = stocks_data.loc[
    (stocks_data['Date'] == first_porto_date), ['Ticker', 'Date']
]

# 3. Select data return aktual untuk evaluasi nanti
return_porto = stocks_data.loc[
    (stocks_data['Date'] == first_porto_date), ['Ticker', 'Date', 'Rt+1']
]

def get_return_pred_data(data,
                         porto_date,
                         feature_cols,
                         scaler): # Tambahkan parameter scaler
    """
    Mekanisme: Mengambil data fitur pada tanggal konstruksi portofolio
    dan menyamakannya dengan skala data training.
    """
    data = data.copy()

    # 1. Select Fitur (X)
    X_porto = data.loc[
        (data['Date'] == porto_date), feature_cols
    ]

    # Perubahan: Jika data ditemukan, lakukan transformasi skala
    if not X_porto.empty:
        X_porto_scaled = scaler.transform(X_porto) # Gunakan scaler dari data training
        X_porto = pd.DataFrame(X_porto_scaled, columns=feature_cols, index=X_porto.index)

    # 2. Select Identitas (Ticker & Date)
    y_porto = data.loc[
        (data['Date'] == porto_date), ['Ticker', 'Date']
    ]

    # 3. Select Target Aktual (untuk evaluasi backtest)
    return_porto = data.loc[
        (data['Date'] == porto_date), ['Ticker', 'Date', 'Rt+1']
    ]

    return X_porto, y_porto, return_porto

# Tambahkan model_scaler yang didapatkan saat proses training sebelumnya
X_porto, y_porto, return_porto = get_return_pred_data(
    data = stocks_data,
    porto_date = first_porto_date,
    feature_cols = feature,
    scaler = model_scaler # <--- WAJIB ditambahkan
)

# Cek apakah data berhasil diambil
print(f"Jumlah saham yang siap diprediksi pada {first_porto_date}: {len(X_porto)}")

y_porto

X_porto

return_porto

# predict next return

y_porto['Pred Rt+1'] = model.predict(X_porto)
y_porto.head()

# Mekanisme: Membagi saham ke dalam bin (decile) dan mengambil 10% teratas
# Perubahan: Menambahkan 'duplicates=drop' untuk mencegah error jika banyak nilai prediksi yang sama
y_porto['is_porto'] = pd.qcut(
    y_porto['Pred Rt+1'],
    q=[0, 0.9, 1.0],
    labels=[False, True],
    duplicates='drop'
)

# Tambahan: Menampilkan hanya saham yang terpilih masuk portofolio
selected_stocks = y_porto[y_porto['is_porto'] == True].sort_values(by='Pred Rt+1', ascending=False)
print(f"Jumlah saham terpilih: {len(selected_stocks)}")
selected_stocks

# show which stocks belong to our porto
y_porto.loc[
    y_porto['is_porto']==True
]

# filter return data based on portofolio constructed
ticker_list = y_porto.loc[
    y_porto['is_porto']==True,'Ticker'
].unique().tolist()

return_portofolio = return_porto.loc[
    return_porto['Ticker'].isin(ticker_list)
]

return_portofolio['Ticker'].unique()

def construct_portofolio(data, porto_date, feature_cols, model, scaler, percentile):
    # 1. Filter data untuk tanggal konstruksi
    y_porto = data[data['Date'] == porto_date].copy()

    if y_porto.empty:
        return pd.DataFrame()

    # 2. Scaling Fitur
    X_porto = scaler.transform(y_porto[feature_cols])

    # 3. Prediksi menggunakan model
    y_porto['Pred Rt+1'] = model.predict(X_porto)

    # --- PERBAIKAN DI SINI: MENGGANTI qcut DENGAN rank ---
    # Mengurutkan prediksi dari yang terkecil ke terbesar
    # pct=True mengubah rank menjadi persentil (0 sampai 1)
    y_porto['rank_pct'] = y_porto['Pred Rt+1'].rank(pct=True, method='first')

    # Pilih saham yang masuk dalam persentil atas
    # Jika percentile 0.1, maka cari yang rank_pct > 0.9
    bound = 1 - percentile
    y_porto['is_porto'] = y_porto['rank_pct'] > bound

    # Ambil hanya yang terpilih
    selected_porto = y_porto[y_porto['is_porto'] == True].copy()

    return selected_porto

feature = ['FactorMomentum', 'FactorReversal', 'FactorLagReturn-6M']
percentile = 0.1 # top 10%

# Perubahan: Menambahkan parameter scaler agar data fitur di-scale sebelum diprediksi
return_portofolio = construct_portofolio(
    data = stocks_data,
    porto_date = first_porto_date,
    feature_cols = feature,
    model = model,
    scaler = model_scaler, # <--- WAJIB ditambahkan
    percentile = percentile
)

# Menghitung return rata-rata portofolio untuk bulan pertama
print(f"Return Portofolio {first_porto_date.strftime('%Y-%m')}: {return_portofolio['Rt+1'].mean():.2%}")

# Mekanisme: Menghitung Net Return setelah biaya transaksi

FEE = 0.002 # Estimasi biaya beli + jual + pajak (0.5%)



# 1. Menghitung Return Portofolio (Equal Weighted)

avg_raw_return = return_portofolio['Rt+1'].mean()

return_first_month_portofolio = avg_raw_return - FEE



# 2. Perubahan: Menambahkan Benchmark (Rata-rata seluruh saham di bulan yang sama)

# Ini penting untuk melihat "Alpha" (keunggulan strategi)

return_market = return_porto['Rt+1'].mean()



print(f"--- Evaluasi Bulan Pertama ({first_porto_date.strftime('%B %Y')}) ---")

print(f"Gross Return Portfolio : {avg_raw_return:.2%}")

print(f"Net Return (after Fee) : {return_first_month_portofolio:.2%}")

print(f"Market Return          : {return_market:.2%}")

print(f"Alpha vs Market        : {(return_first_month_portofolio - return_market):.2%}")

return_portofolio["Ticker"].unique()

def calculate_portofolio_return(return_porto,FEE) :

    portofolio_return = return_porto['Rt+1'].mean() - FEE
    return portofolio_return

FEE = 0.002
return_first_month_portofolio = calculate_portofolio_return(return_porto=return_portofolio,
                                                            FEE=FEE)
print('Return at first month portofolio using uniform weight',return_first_month_portofolio)

# backtest configuration
start_period = start_date
end_period = end_date
buffer_n_year = 10
percentile = 0.1
FEE = 0.002 # Biaya transaksi per bulan

# Perubahan: Menentukan titik akhir buffer secara otomatis
initial_buffer_end = pd.to_datetime(start_period) + pd.DateOffset(years=buffer_n_year) - pd.offsets.MonthEnd(0)

print(f"Masa Belajar (Training): {start_period} s/d {initial_buffer_end.date()}")
print(f"Masa Investasi (Backtest): {initial_buffer_end.date()} s/d {end_period}")

feature_cols = ['FactorMomentum','FactorReversal','FactorLagReturn-6M']

# # 1. Perbaikan Filter Data: Jangan batasi ke 2022 jika start_period adalah 2009
# stocks_data = stocks_data.copy()
# stocks_data = stocks_data.dropna(subset=['Rt+1']) # Memastikan target return tersedia
# stocks_data = stocks_data.loc[
#     (stocks_data['Date'] >= start_period) & # Gunakan start_period (2009)
#     (stocks_data['Date'] <= end_period)
# ]

# # 2. Inisialisasi Buffer
# initial_buffer_start = pd.to_datetime(start_period)
# initial_buffer_end = initial_buffer_start + pd.DateOffset(years=buffer_n_year) - pd.offsets.MonthEnd(0)
# porto_construction_date = (initial_buffer_end + pd.offsets.MonthEnd(n=1))

# print(f'Backtest Started from {porto_construction_date.date()}')

# collection_return = []
# end_time = pd.to_datetime(end_period)

# # 3. Loop Walk-Forward Validation
# while porto_construction_date <= end_time:
#     print('Constructing Portofolio On:', porto_construction_date.date())

#     # get training data (Pastikan fungsi ini mengembalikan model_scaler juga)
#     # Catatan: Kita butuh scaler untuk fungsi construct_portofolio
#     X_buffer, y_buffer, current_scaler = get_training_data(
#         data=stocks_data,
#         initial_buffer_start=initial_buffer_start,
#         initial_buffer_end=initial_buffer_end,
#         feature_cols=feature_cols
#     )

#     if X_buffer.empty or y_buffer.empty:
#         print(f'-----Skipping: Empty buffer for {porto_construction_date.date()}')
#         net_return = 0.0
#     else:
#         # Training
#         model = train_ml_model(X_train=X_buffer, y_train=y_buffer)

#         # Construct porto (Sertakan current_scaler)
#         return_portofolio = construct_portofolio(
#             data=stocks_data,
#             porto_date=porto_construction_date,
#             feature_cols=feature_cols,
#             model=model,
#             scaler=current_scaler, # Wajib agar prediksi akurat
#             percentile=percentile
#         )

#         if return_portofolio.empty:
#             print(f'-----Skipping: No stocks selected for {porto_construction_date.date()}')
#             net_return = 0.0
#         else:
#             # Calculate Return
#             net_return = calculate_portofolio_return(return_porto=return_portofolio, FEE=FEE)
#             print(f'-----Return: {net_return:.2%}')

#     # Simpan hasil
#     res_df = pd.DataFrame({
#         'ReturnDate': [porto_construction_date + pd.offsets.MonthEnd(n=1)],
#         'PortofolioReturn': [net_return]
#     })
#     collection_return.append(res_df)

#     # Shift period (Mekanisme Rolling Window)
#     initial_buffer_start += pd.offsets.MonthEnd(n=1)
#     initial_buffer_end += pd.offsets.MonthEnd(n=1)
#     porto_construction_date += pd.offsets.MonthEnd(n=1)

# # 1. Menggabungkan semua hasil periodik
# collection_return_df = pd.concat(collection_return, axis=0).reset_index(drop=True)

# # 2. Menghitung Return Kumulatif
# # Perubahan: Menambahkan nilai awal 1.0 agar grafik dimulai dari titik 1 (modal awal)
# collection_return_df['PortofolioCumulativeReturn'] = (1 + collection_return_df['PortofolioReturn']).cumprod()

# # 3. Opsional: Menghitung Drawdown (untuk melihat risiko penurunan terdalam)
# cumulative_max = collection_return_df['PortofolioCumulativeReturn'].cummax()
# collection_return_df['Drawdown'] = (collection_return_df['PortofolioCumulativeReturn'] / cumulative_max) - 1

# print("Hasil Backtest Berhasil Digabungkan.")
# collection_return_df.head()

# mean_return = collection_return_df['PortofolioReturn'].mean()
# print(f'Average Monthly Return : {mean_return*100} %')

# return_volatility = collection_return_df['PortofolioReturn'].std()
# print(f' Monthly Return Volatility : {return_volatility*100} %')

# print('Return Best Case : ',mean_return + 2*return_volatility)
# print('Return Worst Case : ',mean_return - 2*return_volatility)

def report_performance(return_data):
    return_data = return_data.copy()

    # 1. Menghitung Pertumbuhan Kumulatif
    return_data['PortofolioCumulativeReturn'] = (1 + return_data['PortofolioReturn']).cumprod()

    # 2. Statistik Dasar (Monthly)
    mean_return = return_data['PortofolioReturn'].mean()
    return_volatility = return_data['PortofolioReturn'].std()

    # 3. Perubahan: Menambahkan Annualized Sharpe Ratio
    # (Asumsi Risk-Free Rate = 0, disetahunkan dengan akar 12)
    sharpe_ratio = (mean_return / return_volatility) * (12**0.5) if return_volatility != 0 else 0

    # 4. Perubahan: Menambahkan Total Return Akhir
    total_return = (return_data['PortofolioCumulativeReturn'].iloc[-1] - 1) * 100

    print(f"{'='*30}")
    print(f"PERFORMANCE REPORT")
    print(f"{'='*30}")
    print(f"Total Return          : {total_return:.2f} %")
    print(f"Average Monthly Return : {mean_return*100:.2f} %")
    print(f"Monthly Volatility     : {return_volatility*100:.2f} %")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print(f"{'='*30}")

    return return_data, mean_return, return_volatility, sharpe_ratio

# 1. Ambil data IHSG
ihsg_data = yf.Ticker('^JKSE').history(start="2026-01-01", end= end_date)

# 2. Resample ke bulanan (Monthly)
ihsg_monthly = ihsg_data.resample('M').last()
ihsg_monthly = ihsg_monthly.reset_index()

# 3. Hitung Monthly Return
# Perubahan: Menghapus pengurangan FEE untuk Benchmark (IHSG adalah indeks murni)
ihsg_monthly['Return'] = ihsg_monthly['Close'].pct_change()

# 4. Filter tanggal agar pas dengan masa investasi (Backtest)
# Pastikan range ini sama persis dengan 'collection_return_df' Anda
ihsg_return = ihsg_monthly.loc[
    (ihsg_monthly['Date'] >= "2026-01-01") &
    (ihsg_monthly['Date'] <= end_date)
].copy()

# 5. Hitung Cumulative Return
ihsg_return['CumReturn'] = (1 + ihsg_return['Return'].fillna(0)).cumprod()

ihsg_return = ihsg_return[['Date', 'Return', 'CumReturn']]
ihsg_return

# fig = plt.figure(figsize=(12,6))

# sns.lineplot(x=collection_return_df['ReturnDate'],
#              y=collection_return_df['PortofolioCumulativeReturn'],label='ML Porto Uniform (Top 10%)')
# sns.lineplot(x=ihsg_return['Date'],
#              y=ihsg_return['CumReturn'],label='IHSG Return ')
# plt.title('Cumulative Return , FEE 0.5%')

def run_backtest(stocks_data,
                 start_period,
                 end_period,
                 percentile,
                 buffer_n_year,
                 feature_cols,
                 FEE):

    # 1. Perbaikan Filter Data (Wajib diassign kembali ke variabel)
    stocks_data = stocks_data.copy()
    stocks_data = stocks_data.loc[
        (stocks_data['Date'] >= start_period) &
        (stocks_data['Date'] <= end_period)
    ]

    # Inisialisasi Periode
    initial_buffer_start = pd.to_datetime(start_period)
    initial_buffer_end = initial_buffer_start + pd.DateOffset(years=buffer_n_year) - pd.offsets.MonthEnd(0)
    porto_construction_date = (initial_buffer_end + pd.offsets.MonthEnd(n=1))
    end_time = pd.to_datetime(end_period)

    collection_return = []

    try:
        while porto_construction_date <= end_time:
            print(f'Constructing Portfolio On: {porto_construction_date.date()}')

            # 2. Get Training Data & Scaler
            # Mekanisme: Mengambil data historis dan scaler yang fit pada data tersebut
            X_buffer, y_buffer, current_scaler = get_training_data(
                data=stocks_data,
                initial_buffer_start=initial_buffer_start,
                initial_buffer_end=initial_buffer_end,
                feature_cols=feature_cols
            )

            if X_buffer.empty:
                print('-----Skipping: No training data available')
            else:
                # 3. Training
                model = train_ml_model(X_train=X_buffer, y_train=y_buffer)

                # 4. Construct Portfolio (Melewatkan current_scaler)
                res_porto = construct_portofolio(
                    data=stocks_data,
                    porto_date=porto_construction_date,
                    feature_cols=feature_cols,
                    model=model,
                    scaler=current_scaler, # Penting agar prediksi akurat
                    percentile=percentile
                )

                if not res_porto.empty:
                    print('-----Calculating Return')
                    monthly_net_return = calculate_portofolio_return(return_porto=res_porto, FEE=FEE)

                    porto_return_df = pd.DataFrame({
                        'ReturnDate': [porto_construction_date + pd.offsets.MonthEnd(n=1)],
                        'PortofolioReturn': [monthly_net_return]
                    })
                    collection_return.append(porto_return_df)

            # 5. Shift Periode (Rolling Window Mechanism)
            initial_buffer_start += pd.offsets.MonthEnd(n=1)
            initial_buffer_end += pd.offsets.MonthEnd(n=1)
            porto_construction_date += pd.offsets.MonthEnd(n=1)

    except Exception as e:
        print(f"An error occurred: {e}")

    finally:
        print('Preparing Performance Report')
        if collection_return:
            collection_return_df = pd.concat(collection_return, axis=0).reset_index(drop=True)
            # Menghasilkan laporan akhir
            res_report = report_performance(return_data=collection_return_df)
            return res_report # Mengembalikan data, mean, vol, dan sharpe
        else:
            print("No portfolio returns to calculate.")
            return None

backtest_config = {
    'stocks_data' : stocks_data ,
    'start_period' : start_date,
    'end_period' : end_date,
    'percentile' : 0.1,  # top 30%
    'buffer_n_year' : 10 ,
    'feature_cols' : ['FactorMomentum','FactorReversal','FactorLagReturn-6M'] ,
    'FEE' : 0.002
}
top10= run_backtest(**backtest_config)

backtest_config = {
    'stocks_data' : stocks_data ,
    'start_period' : start_date,
    'end_period' : end_date,
    'percentile' : 0.3,  # top 30%
    'buffer_n_year' : 10 ,
    'feature_cols' : ['FactorMomentum','FactorReversal','FactorLagReturn-6M'] ,
    'FEE' : 0.002
}
top30= run_backtest(**backtest_config)

backtest_config2= {
    'stocks_data' : stocks_data ,
    'start_period' : start_date,
    'end_period' :end_date,
    'percentile' : 0.5,  # top 50%
    'buffer_n_year' : 10 ,
    'feature_cols' : ['FactorMomentum','FactorReversal','FactorLagReturn-6M'] ,
    'FEE' : 0.002
}
top50= run_backtest(**backtest_config2)

top = 10/len(data['Ticker'].unique())
top

backtest_config2= {
    'stocks_data' : stocks_data ,
    'start_period' : start_date,
    'end_period' :end_date,
    'percentile' : top,  # top 50%
    'buffer_n_year' : 10 ,
    'feature_cols' : ['FactorMomentum','FactorReversal','FactorLagReturn-6M'] ,
    'FEE' : 0.002
}
top10besar= run_backtest(**backtest_config2)

fig = plt.figure(figsize=(14, 7))

# Perhatikan penggunaan [0] jika variabel tersebut adalah Tuple hasil return fungsi
# Kita pastikan mengambil DataFrame-nya saja

# Plot Top 10%
sns.lineplot(x=top10[0]['ReturnDate'],
             y=top10[0]['PortofolioCumulativeReturn'],
             label='Top 10% (High Conviction)', linewidth=2)

# Plot Top 30%
sns.lineplot(x=top30[0]['ReturnDate'],
             y=top30[0]['PortofolioCumulativeReturn'],
             label='Top 30% (Balanced)', alpha=0.8)

# Plot Top 50%
sns.lineplot(x=top50[0]['ReturnDate'],
             y=top50[0]['PortofolioCumulativeReturn'],
             label='Top 50% (Broad Market)', alpha=0.7)

# Plot IHSG Benchmark
sns.lineplot(x=ihsg_return['Date'],
             y=ihsg_return['CumReturn'],
             label='IHSG (Benchmark)', color='black', linestyle='--')

# Plot Strategi Baru kamu (Top 10 Saham Fix)
# Pastikan mengecek apakah top10besar juga perlu index [0] atau tidak
if isinstance(top10besar, tuple):
    data_plot_baru = top10besar[0]
else:
    data_plot_baru = top10besar

sns.lineplot(x=data_plot_baru['ReturnDate'],
             y=data_plot_baru['PortofolioCumulativeReturn'],
             label='Top 10 Saham (Fixed)', color='blue', linewidth=2.5)

plt.axhline(1, color='red', linestyle=':', alpha=0.5, label='Break Even')
plt.title('Comparison of Cumulative Returns: AI Portfolio Concentration (FEE 0.5%)', fontsize=14)
plt.ylabel('Growth of 1 Unit of Capital')
plt.xlabel('Date')
plt.legend()
plt.grid(True, alpha=0.2)
plt.show()

fig = plt.figure(figsize=(12,6))

# Tambahkan [0] pada top10 jika itu hasil return dari fungsi yang sama dengan top30/top50
sns.lineplot(x=top10[0]['ReturnDate'],
             y=top10[0]['PortofolioCumulativeReturn'],
             label='Top 10% ML Porto Uniform', linewidth=2)

sns.lineplot(x=top30[0]['ReturnDate'],
             y=top30[0]['PortofolioCumulativeReturn'],
             label='Top 30% ML Porto Uniform')

sns.lineplot(x=top50[0]['ReturnDate'],
             y=top50[0]['PortofolioCumulativeReturn'],
             label='Top 50% ML Porto Uniform')

sns.lineplot(x=ihsg_return['Date'],
             y=ihsg_return['CumReturn'],
             label='IHSG Return', color='black', linestyle='--')

plt.title('Cumulative Return Comparison (FEE 0.5%)', fontsize=14)
plt.ylabel('Cumulative Return')
plt.xlabel('Date')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()